#ifndef CONSTANTES_SEH_H_INCLUDED
#define CONSTANTES_SEH_H_INCLUDED

#define ARCHIVO_P "archivo_pisos.bin" /// ARCHIVO DONDE SE GUARDA/LEE LA INFORMACION PARA MANTENER NUESTRO HOTEL

#endif // CONSTANTES_SEH_H_INCLUDED
