#ifndef STS_SEH_H_INCLUDED
#define STS_SEH_H_INCLUDED
                /// ESTRUCTURAS DE NODOS

        /// NODO PISO ( NODO LDL, COMPONE LOS PISOS CON SUS HABITACIONES )




                /// ESTRUCTURA PARA LECTURA/ESCRITURA DE HAB EN ARCHIVO BINARIO






#endif // STS_SEH_H_INCLUDED
